# 公共配置文件
# 
# 
spring:
  application:
    name: stars-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wake
    username: root
    password: 123123
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
#    password: 123456
    #rabbitmq 配置
  rabbitmq:
    port: 5672
    host: localhost
    password: guest
    username: guest
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-interval: 600000
          initial-interval: 5000 #初始间隔为5s
          max-attempts: 30 # 最大尝试次数
          multiplier: 1 #重试间隔的乘数
        #开启重试机制
      simple:
        acknowledge-mode: manual #手动确认
        retry:
          enabled: true
          max-interval: 600000
          initial-interval: 5000 #初始间隔为5s
          max-attempts: 30 # 最大尝试次数
          multiplier: 1 #重试间隔的乘数

    publisher-confirm-type: correlated #发布消息成功到交换器后会触发回调方法
    publisher-returns: true #消息已经投递给交换机，但路由到队列的过程中失败了，返回 ack 和路由失败原因
    template:
      mandatory: true #当消息传递过程中不可达目的地时将消息返回给生产者。即回退消息

  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）




